// This file is auto-generated by @hey-api/openapi-ts

export type ListResultDto_IdentityRoleDto = {
    items?: Array<Volo_Abp_Identity_IdentityRoleDto> | null;
};

export type ListResultDto_UserData = {
    items?: Array<Volo_Abp_Users_UserData> | null;
};

export type PagedResultDto_IdentityRoleDto = {
    items?: Array<Volo_Abp_Identity_IdentityRoleDto> | null;
    totalCount?: number;
};

export type PagedResultDto_IdentityUserDto = {
    items?: Array<Volo_Abp_Identity_IdentityUserDto> | null;
    totalCount?: number;
};

export type PagedResultDto_ListMemberResponseDto = {
    items?: Array<TahsilEt_Members_ListMemberResponseDto> | null;
    totalCount?: number;
};

export type PagedResultDto_ListTransactionResponseDto = {
    items?: Array<TahsilEt_Transactions_ListTransactionResponseDto> | null;
    totalCount?: number;
};

export type PagedResultDto_TenantDto = {
    items?: Array<Volo_Abp_TenantManagement_TenantDto> | null;
    totalCount?: number;
};

export type TahsilEt_Members_DeleteMemberDto = {
    idType: TahsilEt_Members_IdType;
    identifier: string;
};

export type TahsilEt_Members_DeleteMemberResponseDto = {
    kfsReturnMessageRef: string;
    prepDateTime?: (string) | null;
    receiverMessageReference: string;
    responseCode: string;
    responseDesc: string;
};

export type TahsilEt_Members_IdType = 'NONE' | 'TCKN' | 'SCL' | 'YKN' | 'VKN' | 'MKN';

export type TahsilEt_Members_ListMemberResponseDto = {
    id: string;
    type: TahsilEt_Members_Type;
    idType: TahsilEt_Members_IdType;
    identifier: string;
    paymentFreqDays: number;
    name?: (string) | null;
    surname?: (string) | null;
    title?: (string) | null;
    tel?: (string) | null;
    mail: string;
    mobile?: (string) | null;
    isInvestor?: boolean;
    isEntrepreneur?: boolean;
    qualifiedCheck?: boolean;
    fullNameCheck?: boolean;
    isValidated?: boolean;
};

export type TahsilEt_Members_MemberFilterDto = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: (string) | null;
    id?: (string) | null;
    type?: TahsilEt_Members_Type;
    idType?: TahsilEt_Members_IdType;
    identifier?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    title?: (string) | null;
    tel?: (string) | null;
    mail?: (string) | null;
    isValidated?: (boolean) | null;
    isEntrepreneur?: (boolean) | null;
    isInvestor?: (boolean) | null;
};

export type TahsilEt_Members_SaveMemberDto = {
    type: TahsilEt_Members_Type;
    idType: TahsilEt_Members_IdType;
    identifier: string;
    paymentFreqDays: number;
    name?: (string) | null;
    surname?: (string) | null;
    title?: (string) | null;
    tel?: (string) | null;
    mail: string;
    mobile?: (string) | null;
};

export type TahsilEt_Members_SaveMemberResponseDto = {
    kfsReturnMessageRef?: (string) | null;
    prepDateTime?: (string) | null;
    receiverPlatformId?: (string) | null;
    receiverMessageReference?: (string) | null;
    responseCode?: (string) | null;
    responseDesc?: (string) | null;
    id: string;
};

export type TahsilEt_Members_Type = 'NONE' | 'Individual' | 'Organization';

export type TahsilEt_Members_UpdateMemberDto = {
    type: TahsilEt_Members_Type;
    idType: TahsilEt_Members_IdType;
    identifier: string;
    paymentFreqDays: number;
    name?: (string) | null;
    surname?: (string) | null;
    title?: (string) | null;
    tel?: (string) | null;
    mobile?: (string) | null;
    mail?: (string) | null;
};

export type TahsilEt_Members_UpdateMemberResponseDto = {
    kfsReturnMessageRef: string;
    prepDateTime?: (string) | null;
    receiverPlatformId: string;
    receiverMessageReference: string;
    responseCode: string;
    responseDesc: string;
};

export type TahsilEt_PayRecs_Enums_PayRecSign = 'Credit' | 'Debit';

export type TahsilEt_PayRecs_PayRecDto = {
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    readonly tenantId?: (string) | null;
    sign: TahsilEt_PayRecs_Enums_PayRecSign;
    transactionDate: string;
    dueDate?: (string) | null;
    amount: number;
    paidAmount?: (number) | null;
    logicalRef: (string) | null;
    ficheRef?: (string) | null;
    crossRef?: (string) | null;
    memberId: string;
};

export type TahsilEt_Transactions_ClosePaymentsFifoDto = {
    memberId: string;
};

export type TahsilEt_Transactions_CreateTransactionDto = {
    memberId: string;
    transactionType: TahsilEt_Transactions_Enums_TransactionType;
    transactionDate: string;
    debit?: (number) | null;
    credit?: (number) | null;
    documentType?: TahsilEt_Transactions_Enums_DocumentType;
};

export type TahsilEt_Transactions_CreateTransactionResponseDto = {
    id?: string;
};

export type TahsilEt_Transactions_DeleteTransactionResponseDto = {
    [key: string]: unknown;
};

export type TahsilEt_Transactions_Enums_DocumentType = 'Invoice' | 'Check' | 'PromissoryNote' | 'CreditCard' | 'Cash';

export type TahsilEt_Transactions_Enums_TransactionType = 'Credit' | 'Debit';

export type TahsilEt_Transactions_GetScorePredictionResponseDto = {
    score: number;
    riskGroup: TahsilEt_Transactions_RiskGroup;
};

export type TahsilEt_Transactions_ListTransactionResponseDto = {
    id: string;
    memberId: string;
    transactionType: TahsilEt_Transactions_Enums_TransactionType;
    transactionDate: string;
    debit: (number) | null;
    credit: (number) | null;
    documentType: TahsilEt_Transactions_Enums_DocumentType;
    logicalRef: (string) | null;
    payRecs?: Array<TahsilEt_PayRecs_PayRecDto> | null;
};

export type TahsilEt_Transactions_RiskGroup = 'CokIyi' | 'Iyi' | 'AzRiskli' | 'OrtaRiskli' | 'CokRiskli';

export type TahsilEt_Transactions_ScoreParamsResponseDto = {
    cardRef: (string) | null;
    procDate: string;
    paidInvoice: boolean;
    totalPaidInvoices: number;
    sumAmountPaidInvoices: number;
    totalInvoiceLate: number;
    sumAmountLateInvoices: number;
    totalOutstandingInvoices: number;
    totalOutStandingLate: number;
    sumTotalOutStanding: number;
    sumLateOutStanding: number;
    averagePaymentDate: number;
    averageDaysOutStandingLate: number;
    score: number;
    riskGroup: TahsilEt_Transactions_RiskGroup;
};

export type TahsilEt_Transactions_TransactionFilterDto = {
    maxResultCount?: number;
    skipCount?: number;
    sorting?: (string) | null;
    id?: (string) | null;
    memberId?: (string) | null;
    transactionType?: TahsilEt_Transactions_Enums_TransactionType;
    transactionDate?: (string) | null;
    debit?: (number) | null;
    credit?: (number) | null;
    documentType?: TahsilEt_Transactions_Enums_DocumentType;
    logicalRef?: (string) | null;
};

export type TahsilEt_Transactions_UnpaidTransactionDto = {
    id: string;
    memberId: string;
    transactionType: TahsilEt_Transactions_Enums_TransactionType;
    transactionDate: string;
    debit: (number) | null;
    credit: (number) | null;
    dueDate: string;
    documentType: TahsilEt_Transactions_Enums_DocumentType;
    logicalRef: (string) | null;
    countDaysLate: number;
    isLate: boolean;
};

export type TahsilEt_Transactions_UpdateTransactionDto = {
    transactionType?: TahsilEt_Transactions_Enums_TransactionType;
    transactionDate?: (string) | null;
    debit?: (number) | null;
    credit?: (number) | null;
    documentType?: TahsilEt_Transactions_Enums_DocumentType;
};

export type TahsilEt_Transactions_UpdateTransactionResponseDto = {
    [key: string]: unknown;
};

export type Volo_Abp_Account_ChangePasswordInput = {
    currentPassword?: (string) | null;
    newPassword: string;
};

export type Volo_Abp_Account_ProfileDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName?: (string) | null;
    email?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    phoneNumber?: (string) | null;
    isExternal?: boolean;
    hasPassword?: boolean;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Account_RegisterDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName: string;
    emailAddress: string;
    password: string;
    appName: string;
};

export type Volo_Abp_Account_ResetPasswordDto = {
    userId?: string;
    resetToken: string;
    password: string;
};

export type Volo_Abp_Account_SendPasswordResetCodeDto = {
    email: string;
    appName: string;
    returnUrl?: (string) | null;
    returnUrlHash?: (string) | null;
};

export type Volo_Abp_Account_UpdateProfileDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName?: (string) | null;
    email?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    phoneNumber?: (string) | null;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Account_VerifyPasswordResetTokenInput = {
    userId?: string;
    resetToken: string;
};

export type Volo_Abp_Account_Web_Areas_Account_Controllers_Models_AbpLoginResult = {
    result?: Volo_Abp_Account_Web_Areas_Account_Controllers_Models_LoginResultType;
    readonly description?: (string) | null;
};

export type Volo_Abp_Account_Web_Areas_Account_Controllers_Models_LoginResultType = 'Success' | 'InvalidUserNameOrPassword' | 'NotAllowed' | 'LockedOut' | 'RequiresTwoFactor';

export type Volo_Abp_Account_Web_Areas_Account_Controllers_Models_UserLoginInfo = {
    userNameOrEmailAddress: string;
    password: string;
    rememberMe?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto = {
    grantedPolicies?: {
        [key: string]: (boolean);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto = {
    localization?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto;
    auth?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto;
    setting?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto;
    currentUser?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto;
    features?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto;
    globalFeatures?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto;
    multiTenancy?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto;
    currentTenant?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto;
    timing?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto;
    clock?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto;
    objectExtensions?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto;
    extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto = {
    enabledFeatures?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto = {
    values?: {
        [key: string]: {
            [key: string]: (string);
        };
    } | null;
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    languages?: Array<Volo_Abp_Localization_LanguageInfo> | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
    defaultResourceName?: (string) | null;
    languagesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
    languageFilesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto = {
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto = {
    texts?: {
        [key: string]: (string);
    } | null;
    baseResources?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto = {
    kind?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto = {
    displayName?: (string) | null;
    englishName?: (string) | null;
    threeLetterIsoLanguageName?: (string) | null;
    twoLetterIsoLanguageName?: (string) | null;
    isRightToLeft?: boolean;
    cultureName?: (string) | null;
    name?: (string) | null;
    nativeName?: (string) | null;
    dateTimeFormat?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto = {
    isAuthenticated?: boolean;
    id?: (string) | null;
    tenantId?: (string) | null;
    impersonatorUserId?: (string) | null;
    impersonatorTenantId?: (string) | null;
    impersonatorUserName?: (string) | null;
    impersonatorTenantName?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surName?: (string) | null;
    email?: (string) | null;
    emailVerified?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberVerified?: boolean;
    roles?: Array<(string)> | null;
    sessionId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto = {
    calendarAlgorithmType?: (string) | null;
    dateTimeFormatLong?: (string) | null;
    shortDatePattern?: (string) | null;
    fullDateTimePattern?: (string) | null;
    dateSeparator?: (string) | null;
    shortTimePattern?: (string) | null;
    longTimePattern?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone = {
    timeZoneName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto = {
    properties?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto = {
    fields?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto> | null;
    localizationResource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto = {
    name?: (string) | null;
    value?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto = {
    onGet?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto;
    onCreate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto;
    onUpdate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto = {
    typeSimple?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto = {
    type?: (string) | null;
    typeSimple?: (string) | null;
    displayName?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto;
    api?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto;
    ui?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto;
    policy?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyPolicyDto;
    attributes?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto> | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
    defaultValue?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyFeaturePolicyDto = {
    features?: Array<(string)> | null;
    requiresAll?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyGlobalFeaturePolicyDto = {
    features?: Array<(string)> | null;
    requiresAll?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyPermissionPolicyDto = {
    permissionNames?: Array<(string)> | null;
    requiresAll?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyPolicyDto = {
    globalFeatures?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyGlobalFeaturePolicyDto;
    features?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyFeaturePolicyDto;
    permissions?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyPermissionPolicyDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto = {
    onTable?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto;
    onCreateForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    onEditForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    lookup?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto = {
    url?: (string) | null;
    resultListPropertyName?: (string) | null;
    displayPropertyName?: (string) | null;
    valuePropertyName?: (string) | null;
    filterParamName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto = {
    name?: (string) | null;
    resource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto = {
    entities?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto = {
    modules?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto;
    } | null;
    enums?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone = {
    iana?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone;
    windows?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto = {
    timeZone?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone = {
    timeZoneId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto = {
    id?: (string) | null;
    name?: (string) | null;
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto = {
    success?: boolean;
    tenantId?: (string) | null;
    name?: (string) | null;
    normalizedName?: (string) | null;
    isActive?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto = {
    isEnabled?: boolean;
};

export type Volo_Abp_FeatureManagement_FeatureDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    value?: (string) | null;
    provider?: Volo_Abp_FeatureManagement_FeatureProviderDto;
    description?: (string) | null;
    valueType?: Volo_Abp_Validation_StringValues_IStringValueType;
    depth?: number;
    parentName?: (string) | null;
};

export type Volo_Abp_FeatureManagement_FeatureGroupDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    features?: Array<Volo_Abp_FeatureManagement_FeatureDto> | null;
};

export type Volo_Abp_FeatureManagement_FeatureProviderDto = {
    name?: (string) | null;
    key?: (string) | null;
};

export type Volo_Abp_FeatureManagement_GetFeatureListResultDto = {
    groups?: Array<Volo_Abp_FeatureManagement_FeatureGroupDto> | null;
};

export type Volo_Abp_FeatureManagement_UpdateFeatureDto = {
    name?: (string) | null;
    value?: (string) | null;
};

export type Volo_Abp_FeatureManagement_UpdateFeaturesDto = {
    features?: Array<Volo_Abp_FeatureManagement_UpdateFeatureDto> | null;
};

export type Volo_Abp_Http_Modeling_ActionApiDescriptionModel = {
    uniqueName?: (string) | null;
    name?: (string) | null;
    httpMethod?: (string) | null;
    url?: (string) | null;
    supportedVersions?: Array<(string)> | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    parameters?: Array<Volo_Abp_Http_Modeling_ParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
    allowAnonymous?: (boolean) | null;
    implementFrom?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel = {
    modules?: {
        [key: string]: Volo_Abp_Http_Modeling_ModuleApiDescriptionModel;
    } | null;
    types?: {
        [key: string]: Volo_Abp_Http_Modeling_TypeApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerApiDescriptionModel = {
    controllerName?: (string) | null;
    controllerGroupName?: (string) | null;
    isRemoteService?: boolean;
    isIntegrationService?: boolean;
    apiVersion?: (string) | null;
    type?: (string) | null;
    interfaces?: Array<Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel> | null;
    actions?: {
        [key: string]: Volo_Abp_Http_Modeling_ActionApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel = {
    type?: (string) | null;
    name?: (string) | null;
    methods?: Array<Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel> | null;
};

export type Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel = {
    name?: (string) | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
};

export type Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel = {
    name?: (string) | null;
    typeAsString?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
};

export type Volo_Abp_Http_Modeling_ModuleApiDescriptionModel = {
    rootPath?: (string) | null;
    remoteServiceName?: (string) | null;
    controllers?: {
        [key: string]: Volo_Abp_Http_Modeling_ControllerApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ParameterApiDescriptionModel = {
    nameOnMethod?: (string) | null;
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
    constraintTypes?: Array<(string)> | null;
    bindingSourceId?: (string) | null;
    descriptorName?: (string) | null;
};

export type Volo_Abp_Http_Modeling_PropertyApiDescriptionModel = {
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isRequired?: boolean;
    minLength?: (number) | null;
    maxLength?: (number) | null;
    minimum?: (string) | null;
    maximum?: (string) | null;
    regex?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel = {
    type?: (string) | null;
    typeSimple?: (string) | null;
};

export type Volo_Abp_Http_Modeling_TypeApiDescriptionModel = {
    baseType?: (string) | null;
    isEnum?: boolean;
    enumNames?: Array<(string)> | null;
    enumValues?: Array<unknown> | null;
    genericArguments?: Array<(string)> | null;
    properties?: Array<Volo_Abp_Http_Modeling_PropertyApiDescriptionModel> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorInfo = {
    code?: (string) | null;
    message?: (string) | null;
    details?: (string) | null;
    data?: {
        [key: string]: unknown;
    } | null;
    validationErrors?: Array<Volo_Abp_Http_RemoteServiceValidationErrorInfo> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorResponse = {
    error?: Volo_Abp_Http_RemoteServiceErrorInfo;
};

export type Volo_Abp_Http_RemoteServiceValidationErrorInfo = {
    message?: (string) | null;
    members?: Array<(string)> | null;
};

export type Volo_Abp_Identity_IdentityRoleCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isDefault?: boolean;
    isPublic?: boolean;
};

export type Volo_Abp_Identity_IdentityRoleDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    name?: (string) | null;
    isDefault?: boolean;
    isStatic?: boolean;
    isPublic?: boolean;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Identity_IdentityRoleUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isDefault?: boolean;
    isPublic?: boolean;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Identity_IdentityUserCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName: string;
    name?: (string) | null;
    surname?: (string) | null;
    email: string;
    phoneNumber?: (string) | null;
    isActive?: boolean;
    lockoutEnabled?: boolean;
    roleNames?: Array<(string)> | null;
    password: string;
};

export type Volo_Abp_Identity_IdentityUserDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    tenantId?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    email?: (string) | null;
    emailConfirmed?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberConfirmed?: boolean;
    isActive?: boolean;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    lockoutEnd?: (string) | null;
    concurrencyStamp?: (string) | null;
    entityVersion?: number;
    lastPasswordChangeTime?: (string) | null;
};

export type Volo_Abp_Identity_IdentityUserUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName: string;
    name?: (string) | null;
    surname?: (string) | null;
    email: string;
    phoneNumber?: (string) | null;
    isActive?: boolean;
    lockoutEnabled?: boolean;
    roleNames?: Array<(string)> | null;
    password?: (string) | null;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Identity_IdentityUserUpdateRolesDto = {
    roleNames: Array<(string)>;
};

export type Volo_Abp_Localization_LanguageInfo = {
    cultureName?: (string) | null;
    uiCultureName?: (string) | null;
    displayName?: (string) | null;
    readonly twoLetterISOLanguageName?: (string) | null;
};

export type Volo_Abp_NameValue = {
    name?: (string) | null;
    value?: (string) | null;
};

export type Volo_Abp_PermissionManagement_GetPermissionListResultDto = {
    entityDisplayName?: (string) | null;
    groups?: Array<Volo_Abp_PermissionManagement_PermissionGroupDto> | null;
};

export type Volo_Abp_PermissionManagement_PermissionGrantInfoDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    parentName?: (string) | null;
    isGranted?: boolean;
    allowedProviders?: Array<(string)> | null;
    grantedProviders?: Array<Volo_Abp_PermissionManagement_ProviderInfoDto> | null;
};

export type Volo_Abp_PermissionManagement_PermissionGroupDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    displayNameKey?: (string) | null;
    displayNameResource?: (string) | null;
    permissions?: Array<Volo_Abp_PermissionManagement_PermissionGrantInfoDto> | null;
};

export type Volo_Abp_PermissionManagement_ProviderInfoDto = {
    providerName?: (string) | null;
    providerKey?: (string) | null;
};

export type Volo_Abp_PermissionManagement_UpdatePermissionDto = {
    name?: (string) | null;
    isGranted?: boolean;
};

export type Volo_Abp_PermissionManagement_UpdatePermissionsDto = {
    permissions?: Array<Volo_Abp_PermissionManagement_UpdatePermissionDto> | null;
};

export type Volo_Abp_SettingManagement_EmailSettingsDto = {
    smtpHost?: (string) | null;
    smtpPort?: number;
    smtpUserName?: (string) | null;
    smtpPassword?: (string) | null;
    smtpDomain?: (string) | null;
    smtpEnableSsl?: boolean;
    smtpUseDefaultCredentials?: boolean;
    defaultFromAddress?: (string) | null;
    defaultFromDisplayName?: (string) | null;
};

export type Volo_Abp_SettingManagement_SendTestEmailInput = {
    senderEmailAddress: string;
    targetEmailAddress: string;
    subject: string;
    body?: (string) | null;
};

export type Volo_Abp_SettingManagement_UpdateEmailSettingsDto = {
    smtpHost?: (string) | null;
    smtpPort?: number;
    smtpUserName?: (string) | null;
    smtpPassword?: (string) | null;
    smtpDomain?: (string) | null;
    smtpEnableSsl?: boolean;
    smtpUseDefaultCredentials?: boolean;
    defaultFromAddress: string;
    defaultFromDisplayName: string;
};

export type Volo_Abp_TenantManagement_TenantCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    adminEmailAddress: string;
    adminPassword: string;
};

export type Volo_Abp_TenantManagement_TenantDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    name?: (string) | null;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_TenantManagement_TenantUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Users_UserData = {
    id?: string;
    tenantId?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    isActive?: boolean;
    email?: (string) | null;
    emailConfirmed?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberConfirmed?: boolean;
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_Validation_StringValues_IStringValueType = {
    readonly name?: (string) | null;
    readonly properties?: {
        [key: string]: unknown;
    } | null;
    validator?: Volo_Abp_Validation_StringValues_IValueValidator;
};

export type Volo_Abp_Validation_StringValues_IValueValidator = {
    readonly name?: (string) | null;
    readonly properties?: {
        [key: string]: unknown;
    } | null;
};

export type GetApiAbpApiDefinitionData = {
    ıncludeTypes?: boolean;
};

export type GetApiAbpApiDefinitionResponse = (Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel);

export type GetApiAbpApplicationConfigurationData = {
    ıncludeLocalizationResources?: boolean;
};

export type GetApiAbpApplicationConfigurationResponse = (Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto);

export type GetApiAbpApplicationLocalizationData = {
    cultureName: string;
    onlyDynamics?: boolean;
};

export type GetApiAbpApplicationLocalizationResponse = (Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto);

export type GetApiAbpMultiTenancyTenantsByNameByNameData = {
    name: string;
};

export type GetApiAbpMultiTenancyTenantsByNameByNameResponse = (Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto);

export type GetApiAbpMultiTenancyTenantsByIdByIdData = {
    id: string;
};

export type GetApiAbpMultiTenancyTenantsByIdByIdResponse = (Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto);

export type PostApiAccountRegisterData = {
    requestBody?: Volo_Abp_Account_RegisterDto;
};

export type PostApiAccountRegisterResponse = (Volo_Abp_Identity_IdentityUserDto);

export type PostApiAccountSendPasswordResetCodeData = {
    requestBody?: Volo_Abp_Account_SendPasswordResetCodeDto;
};

export type PostApiAccountSendPasswordResetCodeResponse = (unknown);

export type PostApiAccountVerifyPasswordResetTokenData = {
    requestBody?: Volo_Abp_Account_VerifyPasswordResetTokenInput;
};

export type PostApiAccountVerifyPasswordResetTokenResponse = (boolean);

export type PostApiAccountResetPasswordData = {
    requestBody?: Volo_Abp_Account_ResetPasswordDto;
};

export type PostApiAccountResetPasswordResponse = (unknown);

export type PostApiAccountDynamicClaimsRefreshResponse = (unknown);

export type GetApiSettingManagementEmailingResponse = (Volo_Abp_SettingManagement_EmailSettingsDto);

export type PostApiSettingManagementEmailingData = {
    requestBody?: Volo_Abp_SettingManagement_UpdateEmailSettingsDto;
};

export type PostApiSettingManagementEmailingResponse = (unknown);

export type PostApiSettingManagementEmailingSendTestEmailData = {
    requestBody?: Volo_Abp_SettingManagement_SendTestEmailInput;
};

export type PostApiSettingManagementEmailingSendTestEmailResponse = (unknown);

export type GetApiFeatureManagementFeaturesData = {
    providerKey?: string;
    providerName?: string;
};

export type GetApiFeatureManagementFeaturesResponse = (Volo_Abp_FeatureManagement_GetFeatureListResultDto);

export type PutApiFeatureManagementFeaturesData = {
    providerKey?: string;
    providerName?: string;
    requestBody?: Volo_Abp_FeatureManagement_UpdateFeaturesDto;
};

export type PutApiFeatureManagementFeaturesResponse = (unknown);

export type DeleteApiFeatureManagementFeaturesData = {
    providerKey?: string;
    providerName?: string;
};

export type DeleteApiFeatureManagementFeaturesResponse = (unknown);

export type PostApiAccountLoginData = {
    requestBody?: Volo_Abp_Account_Web_Areas_Account_Controllers_Models_UserLoginInfo;
};

export type PostApiAccountLoginResponse = (Volo_Abp_Account_Web_Areas_Account_Controllers_Models_AbpLoginResult);

export type GetApiAccountLogoutResponse = (unknown);

export type PostApiAccountCheckPasswordData = {
    requestBody?: Volo_Abp_Account_Web_Areas_Account_Controllers_Models_UserLoginInfo;
};

export type PostApiAccountCheckPasswordResponse = (Volo_Abp_Account_Web_Areas_Account_Controllers_Models_AbpLoginResult);

export type DeleteApiMemberByIdData = {
    id: string;
    requestBody?: TahsilEt_Members_DeleteMemberDto;
};

export type DeleteApiMemberByIdResponse = (TahsilEt_Members_DeleteMemberResponseDto);

export type PutApiMemberByIdData = {
    id: string;
    requestBody?: TahsilEt_Members_UpdateMemberDto;
};

export type PutApiMemberByIdResponse = (TahsilEt_Members_UpdateMemberResponseDto);

export type PostApiMemberData = {
    requestBody?: TahsilEt_Members_SaveMemberDto;
};

export type PostApiMemberResponse = (TahsilEt_Members_SaveMemberResponseDto);

export type GetApiMemberData = {
    id?: string;
    identifier?: string;
    idType?: TahsilEt_Members_IdType;
    isEntrepreneur?: boolean;
    isInvestor?: boolean;
    isValidated?: boolean;
    mail?: string;
    maxResultCount?: number;
    name?: string;
    skipCount?: number;
    sorting?: string;
    surname?: string;
    tel?: string;
    title?: string;
    type?: TahsilEt_Members_Type;
};

export type GetApiMemberResponse = (PagedResultDto_ListMemberResponseDto);

export type PostApiAppMemberSaveMemberData = {
    requestBody?: TahsilEt_Members_SaveMemberDto;
};

export type PostApiAppMemberSaveMemberResponse = (TahsilEt_Members_SaveMemberResponseDto);

export type DeleteApiAppMemberByIdMemberData = {
    id: string;
    identifier: string;
    idType: TahsilEt_Members_IdType;
};

export type DeleteApiAppMemberByIdMemberResponse = (TahsilEt_Members_DeleteMemberResponseDto);

export type PutApiAppMemberByIdMemberData = {
    id: string;
    requestBody?: TahsilEt_Members_UpdateMemberDto;
};

export type PutApiAppMemberByIdMemberResponse = (TahsilEt_Members_UpdateMemberResponseDto);

export type PostApiAppMemberListMembersData = {
    requestBody?: TahsilEt_Members_MemberFilterDto;
};

export type PostApiAppMemberListMembersResponse = (PagedResultDto_ListMemberResponseDto);

export type GetApiPermissionManagementPermissionsData = {
    providerKey?: string;
    providerName?: string;
};

export type GetApiPermissionManagementPermissionsResponse = (Volo_Abp_PermissionManagement_GetPermissionListResultDto);

export type PutApiPermissionManagementPermissionsData = {
    providerKey?: string;
    providerName?: string;
    requestBody?: Volo_Abp_PermissionManagement_UpdatePermissionsDto;
};

export type PutApiPermissionManagementPermissionsResponse = (unknown);

export type GetApiAccountMyProfileResponse = (Volo_Abp_Account_ProfileDto);

export type PutApiAccountMyProfileData = {
    requestBody?: Volo_Abp_Account_UpdateProfileDto;
};

export type PutApiAccountMyProfileResponse = (Volo_Abp_Account_ProfileDto);

export type PostApiAccountMyProfileChangePasswordData = {
    requestBody?: Volo_Abp_Account_ChangePasswordInput;
};

export type PostApiAccountMyProfileChangePasswordResponse = (unknown);

export type GetApiIdentityRolesAllResponse = (ListResultDto_IdentityRoleDto);

export type GetApiIdentityRolesData = {
    extraProperties?: {
        [key: string]: unknown;
    };
    filter?: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiIdentityRolesResponse = (PagedResultDto_IdentityRoleDto);

export type PostApiIdentityRolesData = {
    requestBody?: Volo_Abp_Identity_IdentityRoleCreateDto;
};

export type PostApiIdentityRolesResponse = (Volo_Abp_Identity_IdentityRoleDto);

export type GetApiIdentityRolesByIdData = {
    id: string;
};

export type GetApiIdentityRolesByIdResponse = (Volo_Abp_Identity_IdentityRoleDto);

export type PutApiIdentityRolesByIdData = {
    id: string;
    requestBody?: Volo_Abp_Identity_IdentityRoleUpdateDto;
};

export type PutApiIdentityRolesByIdResponse = (Volo_Abp_Identity_IdentityRoleDto);

export type DeleteApiIdentityRolesByIdData = {
    id: string;
};

export type DeleteApiIdentityRolesByIdResponse = (unknown);

export type GetApiMultiTenancyTenantsByIdData = {
    id: string;
};

export type GetApiMultiTenancyTenantsByIdResponse = (Volo_Abp_TenantManagement_TenantDto);

export type PutApiMultiTenancyTenantsByIdData = {
    id: string;
    requestBody?: Volo_Abp_TenantManagement_TenantUpdateDto;
};

export type PutApiMultiTenancyTenantsByIdResponse = (Volo_Abp_TenantManagement_TenantDto);

export type DeleteApiMultiTenancyTenantsByIdData = {
    id: string;
};

export type DeleteApiMultiTenancyTenantsByIdResponse = (unknown);

export type GetApiMultiTenancyTenantsData = {
    filter?: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiMultiTenancyTenantsResponse = (PagedResultDto_TenantDto);

export type PostApiMultiTenancyTenantsData = {
    requestBody?: Volo_Abp_TenantManagement_TenantCreateDto;
};

export type PostApiMultiTenancyTenantsResponse = (Volo_Abp_TenantManagement_TenantDto);

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
    id: string;
};

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = (string);

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
    defaultConnectionString?: string;
    id: string;
};

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = (unknown);

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
    id: string;
};

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = (unknown);

export type GetApiSettingManagementTimezoneResponse = (string);

export type PostApiSettingManagementTimezoneData = {
    timezone?: string;
};

export type PostApiSettingManagementTimezoneResponse = (unknown);

export type GetApiSettingManagementTimezoneTimezonesResponse = (Array<Volo_Abp_NameValue>);

export type DeleteApiTransactionByIdData = {
    id: string;
};

export type DeleteApiTransactionByIdResponse = (TahsilEt_Transactions_DeleteTransactionResponseDto);

export type PutApiTransactionByIdData = {
    id: string;
    requestBody?: TahsilEt_Transactions_UpdateTransactionDto;
};

export type PutApiTransactionByIdResponse = (TahsilEt_Transactions_UpdateTransactionResponseDto);

export type PostApiTransactionData = {
    requestBody?: TahsilEt_Transactions_CreateTransactionDto;
};

export type PostApiTransactionResponse = (TahsilEt_Transactions_CreateTransactionResponseDto);

export type GetApiTransactionData = {
    credit?: number;
    debit?: number;
    documentType?: TahsilEt_Transactions_Enums_DocumentType;
    id?: string;
    logicalRef?: string;
    maxResultCount?: number;
    memberId?: string;
    skipCount?: number;
    sorting?: string;
    transactionDate?: string;
    transactionType?: TahsilEt_Transactions_Enums_TransactionType;
};

export type GetApiTransactionResponse = (PagedResultDto_ListTransactionResponseDto);

export type PostApiTransactionClosePaymentsFifoData = {
    requestBody?: TahsilEt_Transactions_ClosePaymentsFifoDto;
};

export type PostApiTransactionClosePaymentsFifoResponse = (unknown);

export type GetApiTransactionListWithPayRecsData = {
    credit?: number;
    debit?: number;
    documentType?: TahsilEt_Transactions_Enums_DocumentType;
    id?: string;
    logicalRef?: string;
    maxResultCount?: number;
    memberId?: string;
    skipCount?: number;
    sorting?: string;
    transactionDate?: string;
    transactionType?: TahsilEt_Transactions_Enums_TransactionType;
};

export type GetApiTransactionListWithPayRecsResponse = (PagedResultDto_ListTransactionResponseDto);

export type GetApiTransactionScoreParamsByCardRefData = {
    cardRef: string;
};

export type GetApiTransactionScoreParamsByCardRefResponse = (TahsilEt_Transactions_ScoreParamsResponseDto);

export type GetApiTransactionUnpaidTransactionsByMemberIdData = {
    memberId: string;
};

export type GetApiTransactionUnpaidTransactionsByMemberIdResponse = (Array<TahsilEt_Transactions_UnpaidTransactionDto>);

export type GetApiTransactionScorePredictionByCardRefData = {
    cardRef: string;
};

export type GetApiTransactionScorePredictionByCardRefResponse = (TahsilEt_Transactions_GetScorePredictionResponseDto);

export type PostApiAppTransactionTransactionData = {
    requestBody?: TahsilEt_Transactions_CreateTransactionDto;
};

export type PostApiAppTransactionTransactionResponse = (TahsilEt_Transactions_CreateTransactionResponseDto);

export type DeleteApiAppTransactionByIdTransactionData = {
    id: string;
};

export type DeleteApiAppTransactionByIdTransactionResponse = (TahsilEt_Transactions_DeleteTransactionResponseDto);

export type PutApiAppTransactionByIdTransactionData = {
    id: string;
    requestBody?: TahsilEt_Transactions_UpdateTransactionDto;
};

export type PutApiAppTransactionByIdTransactionResponse = (TahsilEt_Transactions_UpdateTransactionResponseDto);

export type PostApiAppTransactionListTransactionsData = {
    requestBody?: TahsilEt_Transactions_TransactionFilterDto;
};

export type PostApiAppTransactionListTransactionsResponse = (PagedResultDto_ListTransactionResponseDto);

export type PostApiAppTransactionListWithPayRecsData = {
    requestBody?: TahsilEt_Transactions_TransactionFilterDto;
};

export type PostApiAppTransactionListWithPayRecsResponse = (PagedResultDto_ListTransactionResponseDto);

export type PostApiAppTransactionClosePaymentsFIfoData = {
    requestBody?: TahsilEt_Transactions_ClosePaymentsFifoDto;
};

export type PostApiAppTransactionClosePaymentsFIfoResponse = (unknown);

export type GetApiAppTransactionScoreParamsData = {
    cardRef?: string;
};

export type GetApiAppTransactionScoreParamsResponse = (TahsilEt_Transactions_ScoreParamsResponseDto);

export type GetApiAppTransactionUnpaidTransactionsByMemberIdData = {
    memberId: string;
};

export type GetApiAppTransactionUnpaidTransactionsByMemberIdResponse = (Array<TahsilEt_Transactions_UnpaidTransactionDto>);

export type GetApiAppTransactionScorePredictionData = {
    cardRef?: string;
};

export type GetApiAppTransactionScorePredictionResponse = (TahsilEt_Transactions_GetScorePredictionResponseDto);

export type GetApiIdentityUsersByIdData = {
    id: string;
};

export type GetApiIdentityUsersByIdResponse = (Volo_Abp_Identity_IdentityUserDto);

export type PutApiIdentityUsersByIdData = {
    id: string;
    requestBody?: Volo_Abp_Identity_IdentityUserUpdateDto;
};

export type PutApiIdentityUsersByIdResponse = (Volo_Abp_Identity_IdentityUserDto);

export type DeleteApiIdentityUsersByIdData = {
    id: string;
};

export type DeleteApiIdentityUsersByIdResponse = (unknown);

export type GetApiIdentityUsersData = {
    extraProperties?: {
        [key: string]: unknown;
    };
    filter?: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiIdentityUsersResponse = (PagedResultDto_IdentityUserDto);

export type PostApiIdentityUsersData = {
    requestBody?: Volo_Abp_Identity_IdentityUserCreateDto;
};

export type PostApiIdentityUsersResponse = (Volo_Abp_Identity_IdentityUserDto);

export type GetApiIdentityUsersByIdRolesData = {
    id: string;
};

export type GetApiIdentityUsersByIdRolesResponse = (ListResultDto_IdentityRoleDto);

export type PutApiIdentityUsersByIdRolesData = {
    id: string;
    requestBody?: Volo_Abp_Identity_IdentityUserUpdateRolesDto;
};

export type PutApiIdentityUsersByIdRolesResponse = (unknown);

export type GetApiIdentityUsersAssignableRolesResponse = (ListResultDto_IdentityRoleDto);

export type GetApiIdentityUsersByUsernameByUserNameData = {
    userName: string;
};

export type GetApiIdentityUsersByUsernameByUserNameResponse = (Volo_Abp_Identity_IdentityUserDto);

export type GetApiIdentityUsersByEmailByEmailData = {
    email: string;
};

export type GetApiIdentityUsersByEmailByEmailResponse = (Volo_Abp_Identity_IdentityUserDto);

export type GetApiIdentityUsersLookupByIdData = {
    id: string;
};

export type GetApiIdentityUsersLookupByIdResponse = (Volo_Abp_Users_UserData);

export type GetApiIdentityUsersLookupByUsernameByUserNameData = {
    userName: string;
};

export type GetApiIdentityUsersLookupByUsernameByUserNameResponse = (Volo_Abp_Users_UserData);

export type GetApiIdentityUsersLookupSearchData = {
    extraProperties?: {
        [key: string]: unknown;
    };
    filter?: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiIdentityUsersLookupSearchResponse = (ListResultDto_UserData);

export type GetApiIdentityUsersLookupCountData = {
    filter?: string;
};

export type GetApiIdentityUsersLookupCountResponse = (number);