export type AbpLocalizationResources = {
  "DisplayName:Abp.Localization.DefaultLanguage": "Default language";
  "Description:Abp.Localization.DefaultLanguage": "The default language of the application.";
};
export type AbpValidationResources = {
  "'{0}' and '{1}' do not match.": "'{0}' and '{1}' do not match.";
  "The {0} field is not a valid credit card number.": "The {0} field is not a valid credit card number.";
  "{0} is not valid.": "{0} is not valid.";
  "The {0} field is not a valid e-mail address.": "The {0} field is not a valid e-mail address.";
  "The {0} field only accepts files with the following extensions: {1}": "The {0} field only accepts files with the following extensions: {1}";
  "The field {0} must be a string or array type with a maximum length of '{1}'.": "The field {0} must be a string or array type with a maximum length of '{1}'.";
  "The field {0} must be a string or array type with a minimum length of '{1}'.": "The field {0} must be a string or array type with a minimum length of '{1}'.";
  "The {0} field is not a valid phone number.": "The {0} field is not a valid phone number.";
  "The field {0} must be between {1} and {2}.": "The field {0} must be between {1} and {2}.";
  "The field {0} must match the regular expression '{1}'.": "The field {0} does not match the requested format.";
  "The {0} field is required.": "The {0} field is required.";
  "The field {0} must be a string with a maximum length of {1}.": "The field {0} must be a string with a maximum length of {1}.";
  "The field {0} must be a string with a minimum length of {2} and a maximum length of {1}.": "The field {0} must be a string with a minimum length of {2} and a maximum length of {1}.";
  "The {0} field is not a valid fully-qualified http, https, or ftp URL.": "The {0} field is not a valid fully-qualified http, https, or ftp URL.";
  "The field {0} is invalid.": "The field {0} is invalid.";
  "The value '{0}' is invalid.": "The value '{0}' is invalid.";
  "The field {0} must be a number.": "The field {0} must be a number.";
  "The field must be a number.": "The field must be a number.";
  "ThisFieldIsNotAValidCreditCardNumber.": "This field is not a valid credit card number.";
  "ThisFieldIsNotValid.": "This field is not valid.";
  "ThisFieldIsNotAValidEmailAddress.": "This field is not a valid e-mail address.";
  "ThisFieldOnlyAcceptsFilesWithTheFollowingExtensions:{0}": "This field only accepts files with the following extensions: {0}";
  "ThisFieldMustBeAStringOrArrayTypeWithAMaximumLengthOf{0}": "This field must be at most '{0}' characters long.";
  "ThisFieldMustBeAStringOrArrayTypeWithAMinimumLengthOf{0}": "This field must be at least '{0}' characters long.";
  "ThisFieldIsNotAValidPhoneNumber.": "This field is not a valid phone number.";
  "ThisFieldMustBeBetween{0}And{1}": "This field must be between {0} and {1}.";
  "ThisFieldMustBeGreaterThanOrEqual{0}": "This field must be greater than or equal to {0}.";
  "ThisFieldMustBeLessOrEqual{0}": "This field must be less than or equal to {0}.";
  "ThisFieldMustMatchTheRegularExpression{0}": "This field must match the regular expression '{0}'.";
  "ThisFieldIsRequired.": "This field is required.";
  "ThisFieldMustBeAStringWithAMaximumLengthOf{0}": "This field must be at most '{0}' characters long.";
  "ThisFieldMustBeAStringWithAMinimumLengthOf{1}AndAMaximumLengthOf{0}": "This field must be at least {1} and at most {0} characters long.";
  ThisFieldIsNotAValidFullyQualifiedHttpHttpsOrFtpUrl: "This field is not a valid fully-qualified http, https, or ftp URL.";
  "ThisFieldIsInvalid.": "This field is invalid.";
};
export type AbpAuditLoggingResources = {
  "Permission:AuditLogging": "Audit logging";
  "Permission:AuditLogs": "Audit logs";
  "Menu:AuditLogging": "Audit logs";
  AuditLogs: "Audit logs";
  HttpStatus: "HTTP status";
  HttpMethod: "HTTP method";
  HttpMethodFilter: "HTTP method filter";
  HttpRequest: "HTTP Request";
  User: "User";
  UserNameFilter: "User filter";
  HasException: "Has exception";
  IpAddress: "IP address";
  Time: "Time";
  Date: "Date";
  Duration: "Duration";
  Detail: "Detail";
  Overall: "Overall";
  Actions: "Actions";
  ClientIpAddress: "Client IP Address";
  ClientName: "Client Name";
  BrowserInfo: "Browser Info";
  Url: "URL";
  UserName: "User name";
  TenantImpersonator: "Tenant Impersonator";
  UserImpersonator: "User Impersonator";
  UrlFilter: "URL filter";
  Exceptions: "Exceptions";
  Comments: "Comments";
  HttpStatusCode: "HTTP status code";
  HttpStatusCodeFilter: "HTTP status code filter";
  ServiceName: "Service";
  MethodName: "Method";
  CorrelationId: "Correlation Id";
  ApplicationName: "Application name";
  ExecutionDuration: "Duration";
  ExtraProperties: "Extra properties";
  MaxDuration: "Max. duration";
  MinDuration: "Min. duration";
  MinMaxDuration: "Duration (Min. - Max.)";
  "{0}Milliseconds": "{0} milliseconds";
  ExecutionTime: "Time";
  Parameters: "Parameters";
  EntityTypeFullName: "Entity Type Full Name";
  Entity: "Entity";
  ChangeType: "Change type";
  ChangeTime: "Time";
  NewValue: "New value";
  OriginalValue: "Original value";
  PropertyName: "Property name";
  PropertyTypeFullName: "Property Type Full Name";
  Yes: "Yes";
  No: "No";
  Changes: "Changes";
  AverageExecutionDurationInLogsPerDay: "Average execution duration";
  AverageExecutionDurationInMilliseconds: "Average execution duration in milliseconds";
  ErrorRateInLogs: "Error rate in logs";
  Success: "Success";
  Fault: "Fault";
  NoChanges: "No change(s)";
  EntityChanges: "Entity changes";
  EntityId: "Entity Id";
  EntityChangeStartTime: "Min change date";
  EntityChangeEndTime: "Max change date";
  EntityHistory: "Entity history";
  DaysAgoTitle: "{0} {1}.";
  DaysAgoWithUserTitle: "{0} {1} by {2}.";
  Created: "Created";
  Updated: "Updated";
  Deleted: "Deleted";
  ChangeHistory: "Change history";
  FullChangeHistory: "Full change history";
  ChangeDetails: "Change details";
  DurationMs: "Duration (ms)";
  StartDate: "Start date";
  EndDate: "End date";
  "Feature:AuditLoggingGroup": "Audit logging";
  "Feature:AuditLoggingEnable": "Enable audit logging page";
  "Feature:AuditLoggingEnableDescription": "Enable audit logging page in the application.";
  "Feature:AuditLoggingSettingManagementEnable": "Enable audit log setting management";
  "Feature:AuditLoggingSettingManagementEnableDescription": "Enable the configuration of the audit log setting management within the application.";
  InvalidAuditLogDeletionSettings: "Invalid audit log deletion settings. If deletion is enable, the period should be greater than 0 days.";
  AuditLogSettingsGeneral: "General";
  AuditLogSettingsGlobal: "Global";
  "DisplayName:IsPeriodicDeleterEnabled": "Enable clean up service system wide";
  "Description:IsPeriodicDeleterEnabled": "If this option is disabled the periodic deleter won't work. Audit logs won't be deleted automatically.";
  "DisplayName:GlobalIsExpiredDeleterEnabled": "Enable clean up service for all tenants and host";
  "Description:GlobalIsExpiredDeleterEnabled": "If this option is enabled all the tenants and the host expired items will be deleted automatically unless it has a specific setting.";
  "DisplayName:IsExpiredDeleterEnabled": "Enable clean up service";
  "Description:IsExpiredDeleterEnabled": "If this option is enabled the expired items will be deleted automatically.";
  "DisplayName:ExpiredDeleterPeriod": "Expired item deletion period";
  "Description:ExpiredDeleterPeriod": "Set the number of days after which expired items will be automatically deleted.";
  ExpiredDeleterPeriodUnit: "day(s)";
  AuditLogsBeforeXWillBeDeleted: "Audit logs before {0} will be deleted.";
};
export type AbpTimingResources = {
  "DisplayName:Abp.Timing.Timezone": "Timezone";
  "Description:Abp.Timing.Timezone": "Application time zone";
};
export type AbpFeatureManagementResources = {
  Features: "Features";
  NoFeatureFoundMessage: "There isn't any available feature.";
  ManageHostFeatures: "Manage host features";
  ManageHostFeaturesText: "You can manage the host side features by clicking the following button.";
  "Permission:FeatureManagement": "Feature management";
  "Permission:FeatureManagement.ManageHostFeatures": "Manage host features";
  "Volo.Abp.FeatureManagement:InvalidFeatureValue": "{0} feature value is not valid!";
  "Menu:FeatureManagement": "Feature management";
  ResetToDefault: "Reset to default";
  ResetedToDefault: "Reseted to default";
  AreYouSure: "Are you sure?";
  AreYouSureToResetToDefault: "Are you sure to reset to default?";
};
export type AbpPermissionManagementResources = {
  Permissions: "Permissions";
  OnlyProviderPermissons: "Only this provider";
  All: "All";
  SelectAllInAllTabs: "Grant all permissions";
  SelectAllInThisTab: "Select all";
  SaveWithoutAnyPermissionsWarningMessage: "Are you sure you want to save without any permissions?";
  PermissionGroup: "Permission Group";
};
export type AbpMultiTenancyResources = {
  TenantNotFoundMessage: "Tenant not found!";
  TenantNotFoundDetails: "There is no tenant with the tenant id or name: {0}";
  TenantNotActiveMessage: "Tenant is not active!";
  TenantNotActiveDetails: "The tenant is not active with the tenant id or name: {0}";
};
export type AbpFeatureResources = {
  "Volo.Feature:010001": "Feature is not enabled: {FeatureName}";
  "Volo.Feature:010002": "Required features are not enabled. All of these features must be enabled: {FeatureNames}";
  "Volo.Feature:010003": "Required features are not enabled. At least one of these features must be enabled: {FeatureNames}";
};
export type AbpSettingManagementResources = {
  Settings: "Settings";
  SavedSuccessfully: "Saved successfully";
  "Permission:SettingManagement": "Setting management";
  "Permission:Emailing": "Emailing";
  "Permission:EmailingTest": "Emailing test";
  "Permission:TimeZone": "Time zone";
  SendTestEmail: "Send test email";
  SenderEmailAddress: "Sender email address";
  TargetEmailAddress: "Target email address";
  Subject: "Subject";
  Body: "Body";
  TestEmailSubject: "Test email {0}";
  TestEmailBody: "Test email body message here";
  SuccessfullySent: "Successfully sent";
  MailSendingFailed: "Mail sending failed, please check your email configuration and try again.";
  Send: "Send";
  "Menu:Emailing": "Emailing";
  "Menu:TimeZone": "Time Zone";
  "DisplayName:Timezone": "Time zone";
  TimezoneHelpText: "This setting is used for application-wide or tenant-based.";
  SmtpHost: "Host";
  SmtpPort: "Port";
  SmtpUserName: "User name";
  SmtpPassword: "Password";
  SmtpDomain: "Domain";
  SmtpEnableSsl: "Enable ssl";
  SmtpUseDefaultCredentials: "Use default credentials";
  DefaultFromAddress: "Default from address";
  DefaultFromDisplayName: "Default from display name";
  "Feature:SettingManagementGroup": "Setting management";
  "Feature:SettingManagementEnable": "Enable setting management";
  "Feature:SettingManagementEnableDescription": "Enable setting management system in the application.";
  "Feature:AllowChangingEmailSettings": "Allow changing email settings.";
  "Feature:AllowChangingEmailSettingsDescription": "Allow changing email settings.";
  SmtpPasswordPlaceholder: "Enter a value to update password";
};
export type AbpIdentityResources = {
  "Menu:IdentityManagement": "Identity management";
  Users: "Users";
  NewUser: "New user";
  UserName: "User name";
  Surname: "Surname";
  EmailAddress: "Email address";
  PhoneNumber: "Phone number";
  UserInformations: "User Information";
  "DisplayName:IsDefault": "Default";
  "DisplayName:IsStatic": "Static";
  "DisplayName:IsPublic": "Public";
  Roles: "Roles";
  Password: "Password";
  PersonalInfo: "My profile";
  PersonalSettings: "Personal settings";
  UserDeletionConfirmationMessage: "User '{0}' will be deleted. Do you confirm that?";
  RoleDeletionConfirmationMessage: "Role '{0}' will be deleted. Do you confirm that?";
  "DisplayName:RoleName": "Role name";
  "DisplayName:UserName": "User name";
  "DisplayName:Name": "Name";
  "DisplayName:Surname": "Surname";
  "DisplayName:Password": "Password";
  "DisplayName:Email": "Email address";
  "DisplayName:PhoneNumber": "Phone number";
  "DisplayName:TwoFactorEnabled": "Two factor verification";
  "DisplayName:IsActive": "Active";
  "DisplayName:LockoutEnabled": "Account lockout";
  "Description:LockoutEnabled": "Lock account after failed login attempts";
  NewRole: "New role";
  RoleName: "Role name";
  CreationTime: "Creation time";
  Permissions: "Permissions";
  "DisplayName:CurrentPassword": "Current password";
  "DisplayName:NewPassword": "New password";
  "DisplayName:NewPasswordConfirm": "Confirm new password";
  PasswordChangedMessage: "Your password has been changed successfully.";
  PersonalSettingsSavedMessage: "Your personal settings has been saved successfully.";
  "Volo.Abp.Identity:DefaultError": "An unknown failure has occurred.";
  "Volo.Abp.Identity:ConcurrencyFailure": "Optimistic concurrency check has been failed. The entity you're working on has modified by another user. Please discard your changes and try again.";
  "Volo.Abp.Identity:DuplicateEmail": "Email '{0}' is already taken.";
  "Volo.Abp.Identity:DuplicateRoleName": "Role name '{0}' is already taken.";
  "Volo.Abp.Identity:DuplicateUserName": "Username '{0}' is already taken.";
  "Volo.Abp.Identity:InvalidEmail": "Email '{0}' is invalid.";
  "Volo.Abp.Identity:InvalidPasswordHasherCompatibilityMode": "The provided PasswordHasherCompatibilityMode is invalid.";
  "Volo.Abp.Identity:InvalidPasswordHasherIterationCount": "The iteration count must be a positive integer.";
  "Volo.Abp.Identity:InvalidRoleName": "Role name '{0}' is invalid.";
  "Volo.Abp.Identity:InvalidToken": "Invalid token.";
  "Volo.Abp.Identity:InvalidUserName": "Username '{0}' is invalid.";
  "Volo.Abp.Identity:LoginAlreadyAssociated": "A user with this login already exists.";
  "Volo.Abp.Identity:PasswordMismatch": "Incorrect password.";
  "Volo.Abp.Identity:PasswordRequiresDigit": "Passwords must have at least one digit ('0'-'9').";
  "Volo.Abp.Identity:PasswordRequiresLower": "Passwords must have at least one lowercase ('a'-'z').";
  "Volo.Abp.Identity:PasswordRequiresNonAlphanumeric": "Passwords must have at least one non alphanumeric character.";
  "Volo.Abp.Identity:PasswordRequiresUpper": "Passwords must have at least one uppercase ('A'-'Z').";
  "Volo.Abp.Identity:PasswordTooShort": "Passwords must be at least {0} characters.";
  "Volo.Abp.Identity:PasswordRequiresUniqueChars": "Passwords must use at least {0} different characters.";
  "Volo.Abp.Identity:RoleNotFound": "Role {0} does not exist.";
  "Volo.Abp.Identity:UserAlreadyHasPassword": "User already has a password set.";
  "Volo.Abp.Identity:UserAlreadyInRole": "User already in role '{0}'.";
  "Volo.Abp.Identity:UserLockedOut": "User is locked out.";
  "Volo.Abp.Identity:UserLockoutNotEnabled": "Lockout is not enabled for this user.";
  "Volo.Abp.Identity:UserNameNotFound": "User {0} does not exist.";
  "Volo.Abp.Identity:UserNotInRole": "User is not in role '{0}'.";
  "Volo.Abp.Identity:PasswordConfirmationFailed": "Password does not match the confirm password.";
  "Volo.Abp.Identity:NullSecurityStamp": "User security stamp cannot be null.";
  "Volo.Abp.Identity:RecoveryCodeRedemptionFailed": "Recovery code redemption failed.";
  "Volo.Abp.Identity:010001": "You can not delete your own account!";
  "Volo.Abp.Identity:010002": "Can not set more than {MaxUserMembershipCount} organization unit for a user!";
  "Volo.Abp.Identity:010003": "Can not change password of an externally logged in user!";
  "Volo.Abp.Identity:010004": "There is already an organization unit with name {0}. Two units with same name can not be created in same level.";
  "Volo.Abp.Identity:010005": "Static roles can not be renamed.";
  "Volo.Abp.Identity:010006": "Static roles can not be deleted.";
  "Volo.Abp.Identity:010007": "You can't change your two factor setting.";
  "Volo.Abp.Identity:010008": "It's not allowed to change two factor setting.";
  "Volo.Abp.Identity:010009": "You can not delegate yourself.";
  "Volo.Abp.Identity:010021": "Name exist: '{0}'.";
  "Identity.OrganizationUnit.MaxUserMembershipCount": "Maximum allowed organization unit membership count for a user";
  ThisUserIsNotActiveMessage: "This user is not active.";
  "Permission:IdentityManagement": "Identity management";
  "Permission:RoleManagement": "Role management";
  "Permission:Create": "Create";
  "Permission:Edit": "Edit";
  "Permission:Delete": "Delete";
  "Permission:ChangePermissions": "Change permissions";
  "Permission:ManageRoles": "Manage roles";
  "Permission:UserManagement": "User management";
  "Permission:UserLookup": "User lookup";
  "DisplayName:Abp.Identity.Password.RequiredLength": "Required length";
  "DisplayName:Abp.Identity.Password.RequiredUniqueChars": "Required unique characters number";
  "DisplayName:Abp.Identity.Password.RequireNonAlphanumeric": "Required non-alphanumeric character";
  "DisplayName:Abp.Identity.Password.RequireLowercase": "Required lower case character";
  "DisplayName:Abp.Identity.Password.RequireUppercase": "Required upper case character";
  "DisplayName:Abp.Identity.Password.RequireDigit": "Required digit";
  "DisplayName:Abp.Identity.Password.ForceUsersToPeriodicallyChangePassword": "Force users to periodically change password";
  "DisplayName:Abp.Identity.Password.PasswordChangePeriodDays": "Password change period(days)";
  "DisplayName:Abp.Identity.Lockout.AllowedForNewUsers": "Enabled for new users";
  "DisplayName:Abp.Identity.Lockout.LockoutDuration": "Lockout duration(seconds)";
  "DisplayName:Abp.Identity.Lockout.MaxFailedAccessAttempts": "Max failed access attempts";
  "DisplayName:Abp.Identity.SignIn.RequireConfirmedEmail": "Require confirmed email";
  "DisplayName:Abp.Identity.SignIn.EnablePhoneNumberConfirmation": "Allow users to confirm their phone number";
  "DisplayName:Abp.Identity.SignIn.RequireConfirmedPhoneNumber": "Require confirmed phone number";
  "DisplayName:Abp.Identity.User.IsUserNameUpdateEnabled": "Allow users to change their usernames";
  "DisplayName:Abp.Identity.User.IsEmailUpdateEnabled": "Allow users to change their email addresses";
  "Description:Abp.Identity.Password.RequiredLength": "The minimum length a password must be.";
  "Description:Abp.Identity.Password.RequiredUniqueChars": "The minimum number of unique characters which a password must contain.";
  "Description:Abp.Identity.Password.RequireNonAlphanumeric": "If passwords must contain a non-alphanumeric character.";
  "Description:Abp.Identity.Password.RequireLowercase": "If passwords must contain a lower case ASCII character.";
  "Description:Abp.Identity.Password.RequireUppercase": "If passwords must contain a upper case ASCII character.";
  "Description:Abp.Identity.Password.RequireDigit": "If passwords must contain a digit.";
  "Description:Abp.Identity.Password.ForceUsersToPeriodicallyChangePassword": "Whether users are forced to periodically change their password.";
  "Description:Abp.Identity.Password.PasswordChangePeriodDays": "The number of days a user's password is valid for.";
  "Description:Abp.Identity.Lockout.AllowedForNewUsers": "Whether a new user can be locked out.";
  "Description:Abp.Identity.Lockout.LockoutDuration": "The duration a user is locked out for when a lockout occurs.";
  "Description:Abp.Identity.Lockout.MaxFailedAccessAttempts": "The number of failed access attempts allowed before a user is locked out, assuming lock out is enabled.";
  "Description:Abp.Identity.SignIn.RequireConfirmedEmail": "Whether a confirmed email address is required to sign in.";
  "Description:Abp.Identity.SignIn.EnablePhoneNumberConfirmation": "Whether the phoneNumber can be confirmed by the user.";
  "Description:Abp.Identity.SignIn.RequireConfirmedPhoneNumber": "Whether a confirmed telephone number is required to sign in.";
  "Description:Abp.Identity.User.IsUserNameUpdateEnabled": "Whether the username can be updated by the user.";
  "Description:Abp.Identity.User.IsEmailUpdateEnabled": "Whether the email can be updated by the user.";
  Details: "Details";
  CreatedBy: "Created by";
  ModifiedBy: "Modified by";
  ModificationTime: "Modification time";
  PasswordUpdateTime: "Password update time";
  LockoutEndTime: "Lockout end time";
  FailedAccessCount: "Failed access count";
};
export type AbpOpenIddictResources = {
  TheOpenIDConnectRequestCannotBeRetrieved: "The OpenID Connect request cannot be retrieved.";
  TheUserDetailsCannotBbeRetrieved: "The user details cannot be retrieved.";
  TheApplicationDetailsCannotBeFound: "The application details cannot be found.";
  DetailsConcerningTheCallingClientApplicationCannotBeFound: "Details concerning the calling client application cannot be found.";
  TheSpecifiedGrantTypeIsNotImplemented: "The specified grant type {0} is not implemented.";
  Authorization: "Authorization";
  DoYouWantToGrantAccessToYourData: "Do you want to grant {0} access to your data?";
  ScopesRequested: "Scopes requested";
  Accept: "Accept";
  Deny: "Deny";
};
export type AbpTenantManagementResources = {
  "Volo.Abp.TenantManagement:DuplicateTenantName": "Tenant name already exist: {Name}";
  "Menu:TenantManagement": "Tenant management";
  Tenants: "Tenants";
  NewTenant: "New tenant";
  TenantName: "Tenant name";
  "DisplayName:TenantName": "Tenant Name";
  TenantDeletionConfirmationMessage: "Tenant '{0}' will be deleted. Do you confirm that?";
  ConnectionStrings: "Connection Strings";
  "DisplayName:DefaultConnectionString": "Default Connection String";
  "DisplayName:UseSharedDatabase": "Use the Shared Database";
  "Permission:TenantManagement": "Tenant management";
  "Permission:Create": "Create";
  "Permission:Edit": "Edit";
  "Permission:Delete": "Delete";
  "Permission:ManageConnectionStrings": "Manage connection strings";
  "Permission:ManageFeatures": "Manage features";
  "DisplayName:AdminEmailAddress": "Admin Email Address";
  "DisplayName:AdminPassword": "Admin Password";
};
export type BlobStoringDatabaseResources = {
  MyAccount: "My account";
};
export type TahsilEtResources = {
  "Menu:Home": "Home";
  "Menu:ContactUs": "Contact Us";
  "Menu:ArticleSample": "Article Sample";
  Home: "Home";
  Welcome: "Welcome";
  LongWelcomeMessage: "Welcome to the application. This is a startup project based on the ABP framework. For more information visit";
  Date: "Date";
  "Permission:Dashboard": "Dashboard";
  "Menu:Dashboard": "Dashboard";
  "Menu:HomePage": "Home page";
  Dashboard: "Dashboard";
  "ExternalProvider:Google": "Google";
  "ExternalProvider:Google:ClientId": "Client ID";
  "ExternalProvider:Google:ClientSecret": "Client secret";
  "ExternalProvider:Microsoft": "Microsoft";
  "ExternalProvider:Microsoft:ClientId": "Client ID";
  "ExternalProvider:Microsoft:ClientSecret": "Client secret";
  "ExternalProvider:Twitter": "Twitter";
  "ExternalProvider:Twitter:ConsumerKey": "Consumer key";
  "ExternalProvider:Twitter:ConsumerSecret": "Consumer secret";
  NewsletterHeader: "Subscribe to the newsletter!";
  NewsletterInfo: "Get information about the latest happenings.";
  NewsletterPreference_Default: "Default newsletter";
  NewsletterPrivacyAcceptMessage: "I accept the <a href='/privacy-policy'>Privacy Policy</a>.";
  Language: "Language";
  Search: "Search";
  LoadMore: "Load more";
  Settings: "Settings";
  Theme: "Theme";
  DeviceTheme: "Device theme";
  Dark: "Dark";
  Light: "Light";
  Unspecified: "System";
  SeeAllUsers: "See all Users";
  TakePhoto: "Take photo";
  ChoosePhoto: "Choose pshoto";
  "Permission:Members": "Members";
  "Permission:Members.Save": "Saving the Members";
  "Permission:Members.Delete": "Delete the Members";
  "Permission:Members.Update": "Update the Members";
  "Permission:Members.List": "List the Members";
  "Permission:Members.All": "All Members";
  "Permission:Transactions": "Transactions";
  "Permission:Transactions.Create": "Create the Transactions";
  "Permission:Transactions.Delete": "Delete the Transactions";
  "Permission:Transactions.Update": "Update the Transactions";
  "Permission:Transactions.List": "List the Transactions";
  "Permission:Transactions.All": "All Transactions";
  "Permission:Projects": "Projects";
  "Permission:Projects.Save": "Saving the Projects";
  "Permission:Projects.Update": "Update the Projects";
  "Permission:Projects.Delete": "Delete the Projects";
  "Permission:Projects.GetTotalBalance": "Total Balance Inquiry Information";
  "Permission:Projects.ProjectLimitQuery": "Project Limit Query";
  "Permission:Projects.List": "List the Projects";
  "Permission:Projects.All": "All Project";
  "Permission:Projects.FundingUpdate": "Funding Update the ProjectPermission";
  "Permission:Projects.FundingDetail": "Funding Detail the ProjectPermission";
  "Permission:Projects.Detail": "Detail the ProjectPermission";
  "Permission:Payments": "Payments";
  "Permission:Payments.Save": "Saving the Payment Transaction";
  "Permission:Payments.List": "List the Payment Transaction";
  "Permission:Payments.All": "All Payment Transaction";
  "Permission:PayRecs": "All Payment Records";
  "Permission:PayRecs.List": "List the Payment Records";
  "Permission:ProjectEntrepreneur": "ProjectEntrepreneur";
  "Permission:ProjectEntrepreneur.Save": "Saving the ProjectEntrepreneur";
  "Permission:ProjectEntrepreneur.Update": "Update the ProjectEntrepreneur";
  "Permission:ProjectEntrepreneur.Delete": "Delete the ProjectEntrepreneur";
  "Permission:ProjectEntrepreneur.List": "List the ProjectEntrepreneur";
  "Permission:CustomPermissions": "CustomPermissions";
  "Permission:CustomPermissions.Save": "Saving the CustomPermissions";
  "Permission:CustomPermissions.Update": "Update the CustomPermissions";
  "Permission:CustomPermissions.Delete": "Delete the CustomPermissions";
  "Permission:CustomPermissions.List": "List the CustomPermissions";
  "Permission:CustomRoles": "CustomRoles";
  "Permission:CustomRoles.Save": "Saving the CustomRoles";
  "Permission:CustomRoles.Update": "Update the CustomRoles";
  "Permission:CustomRoles.Delete": "Delete the CustomRoles";
  "Permission:CustomRoles.List": "List the CustomRoles";
  "Permission:ProjectPermission": "ProjectPermission";
  "Permission:ProjectPermission.Save": "Saving the ProjectPermission";
  "Permission:ProjectPermission.Update": "Update the ProjectPermission";
  "Permission:ProjectPermission.Delete": "Delete the ProjectPermission";
  "Permission:ProjectPermission.List": "List the ProjectPermission";
  "Permission:UserMembers": "UserMembers";
  "Permission:UserMembers.Save": "Saving the UserMembers";
  "Permission:UserMembers.Delete": "Delete the UserMembers";
  "Permission:UserMembers.Update": "Update the UserMembers";
  "Permission:UserMembers.List": "List the UserMembers";
  "Permission:UserMembers.All": "All UserMembers";
  "Permission:Sections": "Sections";
  "Permission:Sections.Save": "Saving the Section and Project";
  "Permission:Sections.Delete": "Delete the Section and Project";
  "Permission:Sections.Update": "Update the Section and Project";
  "Permission:Sections.List": "List the Section and Project";
  "Permission:Sections.All": "All Section and Project";
  "TahsilEt:CustomRoles:BoardMember": "Board Member";
  "TahsilEt:CustomRoles:Co-Founder": "Co-Founder";
  "TahsilEt:CustomRoles:TeamMember": "Team Member";
  "TahsilEt:Sectors:A": "WOODWORKING";
  "TahsilEt:Sectors:B": "ENTERTAINMENT, RECREATION, ORGANIZATION";
  "TahsilEt:Sectors:C": "ELECTRIC, ELECTRONICS, COMPUTER";
  "TahsilEt:Sectors:D": "FOOD, AGRICULTURE";
  "TahsilEt:Sectors:E": "CLOTHING, LEATHER PRODUCTS, HOME TEXTILES, WEAVING";
  "TahsilEt:Sectors:F": "GIFTWARE, EDUCATION, PRINTING, PHOTOGRAPHY, VARIOUS GOODS";
  "TahsilEt:Sectors:G": "HAIRDRESSER, BARBER, CLEANING, SPORTS, COSMETICS, HEALTH";
  "TahsilEt:Sectors:H": "METAL, AUTOMOTIVE, MACHINERY";
  "TahsilEt:Sectors:I": "MARKET, MOBILE";
  "TahsilEt:Sectors:J": "TRANSPORTATION SERVICES";
  "TahsilEt:Sectors:K": "BUILDING ARTS";
  "00000": "Operation Successful";
  EM000: "Message format error";
  EM001: "Message type is not valid.";
  EM003: "You do not have authorization for the address you want to access.";
  EM004: "An unexpected error occurred while processing the message.";
  EM005: "Sender message reference must be unique per platform.";
  EM006: "Welding error";
  EM007: "A request was attempted with an unsupported file ID. The expected value is application/json.";
  "TahsilEt:EM008": "Please try again with a valid JSON.";
  EM009: "Could not find the basic message information to create a message.";
  EM013: "The operation could not be completed due to high volume, please try again.";
  EM014: "An error occurred during the data insertion/update operation because uniqueness could not be ensured. The record you are trying to insert already exists. Please check.";
  "TahsilEt:EM016": "VKN kimlik tipi ile yalnızca unvan bilgisi iletilmelidir.İsim ve soyisim bilgisi iletilmemelidir.";
  "TahsilEt:EM017": "Only name and surname information should be transmitted with the TR ID/YKN/MKN identity type. Title information should not be transmitted.";
  "TahsilEt:EM018": "Enter a valid value for the identity number. This value must be 11 for TR ID/YKN, 10 or 11 for VKN, 11 for MKN, and 8 for Registry.";
  EM024: "The message type in the message content is incompatible with the service.";
  EM031: "No record found for the transmitted ID number and request ID.";
  EM032: "The transmitted ID number and request ID verification result failed.";
  EM040: "The KFS system is temporarily unavailable.";
  EM041: "The license you use to access KFS has expired. Please contact the authorized person.";
  EM042: "The platform code that sent the message does not match the platform code in the message.";
  EM044: "An unexpected error occurred while verifying your license.";
  EM045: "The escrow officer that sent the message does not match the platform code in the message.";
  EM046: "The licensed platform could not be found in the system.";
  EM047: "The license information is invalid.{0}";
  EM048: "The Authorization (License) value could not be found in the header.{0}.";
  EPL01: "Platform kodu geçerli değildir.";
  EPL02: "Fund Collection Type should be Share only.";
  "TahsilEt:EPL03": "There is an active member record for the ID sent on the relevant platform.";
  EPL04: "There is no active member record for the ID sent on the relevant platform.";
  "TahsilEt:EEN01": "Entrepreneur information is not valid. ID could not be found or ID / Name Surname / Title does not match.";
  "TahsilEt:EEN02": "Only one Lead participant should be sent in the Entrepreneur information set.";
  "TahsilEt:EEN03": "There should be at least one Lead participant in the Entrepreneur information set.";
  "TahsilEt:EEN04": "There cannot be more than one record with the same Entrepreneur information in the Entrepreneur information set.";
  "TahsilEt:EPR01": "Project code is not valid. No active Project could be found for the relevant Platform.";
  "TahsilEt:EPR02": "Only $UPDATABLE_PROJECT_FIELDS fields can be updated.";
  EPR03: "The relevant Entrepreneur/Entrepreneurship Company has created a new cannot start a project.";
  EPR04: "The amount of funds collected is not sufficient for the project to be put on hold or successfully completed. Please check";
  EPR05: "The qualification rate is not sufficient for the project to be put on hold or successfully completed. Please check.";
  EPR06: 'The issuance limit upper amount in the last "$PROJECTS_CONTROL_DURATION" month is exceeded, the relevant entrepreneur/startup company cannot start a new project during this period';
  EPR07: "The fundable amount including additional funds has been exceeded. Please check.";
  EPR08: "The project status has been updated as successful, the project cannot be updated again.";
  EPR09: "The current project limit could not be reached.";
  EPR10: "There is an active project with the same name on the relevant platform.";
  EPR11: "Entrepreneur information set could not be found";
  EPR12: "The project status must be 'Successful' in order to enter the company status";
  EPR13: "The qualified rate must be entered as at least 10% for projects over 1,000,000";
  EPR14: "The relevant entrepreneur/enterprise company cannot start a new debt-based project during this period";
  EPR15: 'The issuance limit upper amount in the last "$PROJECTS_CONTROL_DURATION_DBIT" month is exceeded, the relevant entrepreneur/enterprise company cannot start a new debt-based project during this period.';
  EPR18: "For projects with debt type information, no campaigns more than 50% of the discounted value of the cash flows and credit report can be defined.";
  EPR19: "The transmitted Masterreferance information could not be found in the system";
  EPR20: "No other project of the same project type can be started with MasterReference / MasterReference has been used before.";
  EPR22: "The project you want to produce with MASTERREFERANCE must be active.";
  EPR23: "Projects in failed or canceled status cannot be updated as active, waiting or successful.";
  EPR24: "The project you want to produce with MASTERREFERANCE does not have platform compatibility.";
  EPR25: "You have an active project with the same masterreference. The relevant project cannot be updated as successful.";
  EPR26: "You have an unsuccessful/cancelled project with the same masterreference. The relevant project cannot be updated as successful/waiting.";
  EPR27: "The MASTERREFERANCE does not match the lead entrepreneur id information of the project you want to produce.";
  "TahsilEt:EMB01": 'The member information is not valid. ID could not be found or ID / Name Surname / Title does not match. (For legal entities, the title information compatible with the Ministry of Finance will be added to the error message as "UNVAN/..".)';
  EMB02: "No valid registry record could be found in MKS with the transmitted registry information.";
  "TahsilEt:EMB03": 'Only "$UPDATABLE_MEMBER_FIELDS" fields can be updated. (The fields to be updated will be taken from the UPDATABLE_MEMBER_FIELDS parameter.)';
  EMB04: "No active record of the member could be found on the transmitted platform.";
  EMB05: "The member to be deleted has an active funding request. Please check.";
  "TahsilEt:EMB06": "Name and surname or title information should be provided for the registration identity type.";
  EMB07: "Please notify with TR ID/YKN/MKN for this member.";
  ELM01: "The project's open limit is not suitable.";
  ELM03: "The member's open limit is not suitable.";
  ELM04: "No active limit reduction (funding) message could be found for the reference sent in the message on the relevant platform.";
  ELM05: "An unexpected error occurred during member limit update.";
  ELM06: "An unexpected error occurred during project limit update";
  ELM07: "Limit reduction date must be greater than the project start date.";
  ELM08: "A limit increase message has been previously sent for the relevant limit reduction message.";
  ELM09: "For the relevant limit reduction message the amount of partial limit increase transmitted exceeds the total amount.";
  ELM10: "The member's open borrowing limit is not suitable.";
  ELM11: "The member's maximum borrowing amount for this project is not suitable.";
  EPL08: "The platform must perform a transaction based on borrowing for the entrepreneur risk query.";
  EEN10: "There is no record in the YRTS system as of the query date for the ID you transmitted.";
  EM050: "An error was received from the YRTS system";
  ERO03: "The project to which the rights owner is forwarded must have been successfully completed.";
  ERO01: "There is a list of rights owners notified for the same project. To forward a new list, please cancel the relevant notification first.";
  ERO04: "The type of the project forwarded is not compatible with the type information in the content. (DBIT/SHRE)";
  ERO02: "The rights usage notification to be canceled could not be found";
  ECSV1: "CSV field format error. Field: $element.errorColumn";
  ECSV2: "There cannot be more than one row with the same sequence number.";
  ECSV3: "There cannot be more than one row with the same content.";
  ECSV4: "The number of rows cannot be greater than $max_right_owner_csv_count. You can forward the remaining message in a separate part";
  RPR01: "The report type is not valid";
  RPR02: "With the relevant query criterion The transmitted report is empty";
  RPR03: "The report creation date cannot be greater than the current date.";
  RPR04: "The report creation date cannot be {$maxreportrange} before the current date";
  RPR05: "You have an active report link. Please try again after you have completed downloading your active report";
  RPR06: "You have reached the daily maximum number for this report, please try again";
  RPR07: "You can create a report with a maximum of '$.MAX_REPORT_ROWS' rows";
  RPR08: "The link you want to download is not valid / the link is not platform compatible";
  RPR09: "The link you want to download is in preparation. Please try again later";
  RPR10: "The link has been used before or is inactive. Please create a new link";
  RPR11: "Currently busy, please try again later";
  RPR12: "Project id information is entered only for the transaction type report type";
  FLG01: "No action can be taken on the project. Please contact the MKK authorities.";
  EPR28: "The project must be active or successful (for the balance information service)";
  EPR29: "The start date cannot be updated to a later date due to project limits.";
  "TahsilEt:EPR30": "Please enter a valid Identity Type value.";
  "TahsilEt:EPR31": "The current user ID could not be accessed because it is null.";
  "TahsilEt:EPR32": "No records matching the specified criteria were found.";
  "TahsilEt:EPR33": "Member not found.";
  "TahsilEt:EPR34": "A project with this name is available on the platform.";
  "TahsilEt:EPR35": "There is an active project record for the Project ID sent on the relevant platform.";
  "TahsilEt:EPR36": "You do not have authorization for the user you want to update.";
  "TahsilEt:EPR37": "Please enter a valid type value.";
  "TahsilEt:EPR38": "You do not have permissions for the project you want to update.";
  "TahsilEt:EPR39": "The RelatedTransactionID value cannot be null or empty. The operation could not be completed.";
  "TahsilEt:EPR40": "Entrepreuner with ID '{id}' was not found.";
  "TahsilEt:EPR41": "Duplicate record found for PermissionName '{permissionName}' and PermissionType '{permissionType}'.";
  "TahsilEt:EPR42": "Duplicate record found for RolesName '{rolesName}' and RolesType '{rolesType}'.";
  "TahsilEt:EPR43": "The Custom Permission with ID {CustomPermissionId} does not exist.";
  "TahsilEt:EPR44": "The Custom Role with ID {CustomRoleId} does not exist.";
  "TahsilEt:EPR45": "The specified permission already exists and is active.";
  "TahsilEt:EPR46": "This member has already been assigned to the project with this role.";
  "TahsilEt:EPR47": "Custom role  not found: {name} of type {customRoleType}.";
  "TahsilEt:EPR48": "Authorization error: The user does not have manager permission for this project.";
  "TahsilEt:EPR49": "Authorization error: The user does not have the required permission for this project.";
  "TahsilEt:EPR50": "You are not authorized to delete this member.";
  "TahsilEt:EPR51": "You do not have permission to delete this project.";
  "TahsilEt:EPR52": "input cannot be null";
  "TahsilEt:EPR53": "A member with the same MemberId is already associated.";
  "TahsilEt:EPR54": "Only one individual member can be associated with the user.";
  "TahsilEt:EPR55": "The member type must be either 'Organization' or 'Individual'.";
  "TahsilEt:EPR56": "E-State verification has not been completed. Please complete the verification process.";
  "TahsilEt:EPR57": "Your authorization for the payment process is insufficient. Please check your membership permissions or contact the support team.";
  "TahsilEt:EPR58": "Cancellation and refund rights cannot be exercised before payment is confirmed.";
  "TahsilEt:EPR59": "The right of withdrawal cannot be exercised after the payment has been confirmed. This can only be done before confirmation.";
  "TahsilEt:EPR60": "A DecreaseType value must be specified for the return process. Please select an appropriate type.";
  "TahsilEt:EPR61": "No payment was found with the specified RelatedTransactionID. Please provide a valid transaction ID.";
  "TahsilEt:EPR62": "The payment transaction has already been rejected by TakasBank.";
  "TahsilEt:Transactions01": "There is an active transaction record for the ID sent on the relevant platform.";
  "TahsilEt:PayRecs01": "There is an active payment record for the ID sent on the relevant platform.";
};
export type AbpDddApplicationContractsResources = {
  MaxResultCountExceededExceptionMessage: "{0} can not be more than {1}! Increase {2}.{3} on the server side to allow more results.";
};
export type AbpAuthorizationResources = {
  "Volo.Authorization:010001": "Authorization failed! Given policy has not granted.";
  "Volo.Authorization:010002": "Authorization failed! Given policy has not granted: {PolicyName}";
  "Volo.Authorization:010003": "Authorization failed! Given policy has not granted for given resource: {ResourceName}";
  "Volo.Authorization:010004": "Authorization failed! Given requirement has not granted for given resource: {ResourceName}";
  "Volo.Authorization:010005": "Authorization failed! Given requirements has not granted for given resource: {ResourceName}";
};
export type AbpAccountResources = {
  "Menu:Account": "Account";
  UserName: "Username";
  EmailAddress: "Email address";
  UserNameOrEmailAddress: "Username or email address";
  Password: "Password";
  RememberMe: "Remember me";
  UseAnotherServiceToLogin: "Use another service to log in";
  UserLockedOutMessage: "The user account has been locked out due to invalid login attempts. Please wait a while and try again.";
  InvalidUserNameOrPassword: "Invalid username or password!";
  LoginIsNotAllowed: "You are not allowed to log in! Your account is inactive or needs to confirm your email/phone number.";
  SelfRegistrationDisabledMessage: "Self-registration is disabled for this application. Please contact the application administrator to register a new user.";
  LocalLoginDisabledMessage: "Local login is disabled for this application.";
  Login: "Login";
  Cancel: "Cancel";
  Register: "Register";
  AreYouANewUser: "Are you a new user?";
  AlreadyRegistered: "Already registered?";
  InvalidLoginRequest: "Invalid login request";
  ThereAreNoLoginSchemesConfiguredForThisClient: "There are no login schemes configured for this client.";
  LogInUsingYourProviderAccount: "Log in using your {0} account";
  "DisplayName:CurrentPassword": "Current password";
  "DisplayName:NewPassword": "New password";
  "DisplayName:NewPasswordConfirm": "Confirm new password";
  PasswordChangedMessage: "Your password has been changed successfully.";
  "DisplayName:UserName": "Username";
  "DisplayName:Email": "Email";
  "DisplayName:Name": "Name";
  "DisplayName:Surname": "Surname";
  "DisplayName:Password": "Password";
  "DisplayName:EmailAddress": "Email address";
  "DisplayName:PhoneNumber": "Phone number";
  PersonalSettings: "Personal settings";
  PersonalSettingsSaved: "Personal settings saved";
  PersonalSettingsChangedConfirmationModalTitle: "Personal info changed";
  PersonalSettingsChangedConfirmationModalDescription: "The changes will be reflected after logging in again. Do you want to log out now?";
  PasswordChanged: "Password changed";
  NewPasswordConfirmFailed: "Please confirm the new password.";
  NewPasswordSameAsOld: "New password must be different from the old one.";
  Manage: "Manage";
  MyAccount: "My account";
  "DisplayName:Abp.Account.IsSelfRegistrationEnabled": "Is self-registration enabled";
  "Description:Abp.Account.IsSelfRegistrationEnabled": "Whether a user can register the account by him or herself.";
  "DisplayName:Abp.Account.EnableLocalLogin": "Authenticate with a local account";
  "Description:Abp.Account.EnableLocalLogin": "Indicates if the server will allow users to authenticate with a local account.";
  LoggedOutTitle: "Signed Out";
  LoggedOutText: "You have been signed out and you will be redirected soon.";
  ReturnToText: "Click here to return to the application";
  OrLoginWith: "Or login with:";
  ForgotPassword: "Forgot password?";
  SendPasswordResetLink_Information: "A password reset link will be sent to your email to reset your password. If you don't get an email within a few minutes, please retry.";
  PasswordResetMailSentMessage: "Account recovery email sent to your e-mail address. If you don't see this email in your inbox within 15 minutes, look for it in your junk mail folder. If you find it there, please mark it as -Not Junk-. ";
  ResetPassword: "Reset Password";
  ConfirmPassword: "Confirm the password";
  ResetPassword_Information: "Please enter your new password.";
  YourPasswordIsSuccessfullyReset: "Your password is successfully reset.";
  GoToTheApplication: "Go to the application";
  BackToLogin: "Back to login";
  "ProfileTab:Password": "Change password";
  "ProfileTab:PersonalInfo": "Personal info";
  ReturnToApplication: "Return to application";
  "Volo.Account:InvalidEmailAddress": "Can not find the given email address: {0}";
  PasswordReset: "Password reset";
  PasswordResetInfoInEmail: "We received an account recovery request! If you initiated this request, click the following link to reset your password.";
  ResetMyPassword: "Reset my password";
  AccessDenied: "Access denied!";
  AccessDeniedMessage: "You do not have access to this resource.";
  OrRegisterWith: "Or register with";
  RegisterUsingYourProviderAccount: "Register using your {0} account";
};
export type AbpExceptionHandlingResources = {
  InternalServerErrorMessage: "An internal error occurred during your request!";
  ValidationErrorMessage: "Your request is not valid!";
  ValidationNarrativeErrorMessageTitle: "The following errors were detected during validation.";
  DefaultErrorMessage: "An error has occurred!";
  DefaultErrorMessageDetail: "Error detail not sent by the server.";
  DefaultErrorMessage401: "You are not authenticated!";
  DefaultErrorMessage401Detail: "You should sign in to perform this operation.";
  DefaultErrorMessage403: "You are not authorized!";
  DefaultErrorMessage403Detail: "You are not allowed to perform this operation!";
  DefaultErrorMessage404: "Resource not found!";
  DefaultErrorMessage404Detail: "The resource requested could not be found on the server!";
  EntityNotFoundErrorMessage: "There is no entity {0} with id = {1}!";
  AbpDbConcurrencyErrorMessage: "The data you have submitted has already been changed by another user. Discard your changes and try again.";
  Error: "Error";
  UnhandledException: "Unhandled exception!";
  "401Message": "Unauthorized";
  "403Message": "Forbidden";
  "404Message": "Page not found";
  "500Message": "Internal Server Error";
  "403MessageDetail": "You are not authorized to perform this operation!";
  "404MessageDetail": "Sorry, there's nothing at this address.";
  Unauthorized: "Unauthorized";
  invalid_token: "Invalid token";
  SessionExpired: "Your session has expired. Please login again to continue in the application.";
};
export type AbpUiResources = {
  Languages: "Languages";
  AreYouSure: "Are you sure?";
  Cancel: "Cancel";
  Clear: "Clear";
  Yes: "Yes";
  No: "No";
  Ok: "Ok";
  Close: "Close";
  Save: "Save";
  SavingWithThreeDot: "Saving...";
  Actions: "Actions";
  Delete: "Delete";
  CreatedSuccessfully: "Created successfully";
  SavedSuccessfully: "Saved successfully";
  DeletedSuccessfully: "Deleted successfully";
  Edit: "Edit";
  Refresh: "Refresh";
  Language: "Language";
  LoadMore: "Load more";
  ProcessingWithThreeDot: "Processing...";
  LoadingWithThreeDot: "Loading...";
  Welcome: "Welcome";
  Login: "Login";
  Register: "Register";
  Logout: "Log out";
  Submit: "Submit";
  Back: "Back";
  PagerSearch: "Search";
  PagerNext: "Next";
  PagerPrevious: "Previous";
  PagerFirst: "First";
  PagerLast: "Last";
  PagerInfo: "Showing _START_ to _END_ of _TOTAL_ entries";
  "PagerInfo{0}{1}{2}": "Showing {0} to {1} of {2} entries";
  PagerInfoEmpty: "Showing 0 to 0 of 0 entries";
  PagerInfoFiltered: "(filtered from _MAX_ total entries)";
  NoDataAvailableInDatatable: "No data available";
  ErrorLoadingDatatable: "An error occurred during the request. Check the message for details.";
  Total: "total";
  Selected: "selected";
  PagerShowMenuEntries: "Show _MENU_ entries";
  DatatableActionDropdownDefaultText: "Actions";
  ChangePassword: "Change password";
  PersonalInfo: "My profile";
  AreYouSureYouWantToCancelEditingWarningMessage: "You have unsaved changes.";
  GoHomePage: "Go to the homepage";
  GoBack: "Go back";
  Search: "Search";
  ItemWillBeDeletedMessageWithFormat: "{0} will be deleted!";
  ItemWillBeDeletedMessage: "This item will be deleted!";
  ManageYourAccount: "Manage your account";
  OthersGroup: "Other";
  Today: "Today";
  Apply: "Apply";
  InternetConnectionInfo: "The operation could not be performed. Your internet connection is not available at the moment.";
  CopiedToTheClipboard: "Copied to the clipboard";
  AddNew: "Add new";
  ProfilePicture: "Profile picture";
  Theme: "Theme";
  NotAssigned: "Not Assigned";
};
export type AbpUiNavigationResources = {
  "Menu:Administration": "Administration";
};
export type AbpGlobalFeatureResources = {
  "Volo.GlobalFeature:010001": "The '{ServiceName}' service needs to enable '{GlobalFeatureName}' feature.";
};
export type AbpUiMultiTenancyResources = {
  GivenTenantIsNotExist: "Given tenant doesn't exist: {0}";
  GivenTenantIsNotAvailable: "Given tenant isn't available: {0}";
  Tenant: "Tenant";
  Switch: "switch";
  Name: "Name";
  SwitchTenantHint: "Leave the name field blank to switch to the host side.";
  SwitchTenant: "Switch tenant";
  NotSelected: "Not selected";
};
export type AbpEmailingResources = {
  "DisplayName:Abp.Mailing.DefaultFromAddress": "Default from address";
  "DisplayName:Abp.Mailing.DefaultFromDisplayName": "Default from display name";
  "DisplayName:Abp.Mailing.Smtp.Host": "Host";
  "DisplayName:Abp.Mailing.Smtp.Port": "Port";
  "DisplayName:Abp.Mailing.Smtp.UserName": "User name";
  "DisplayName:Abp.Mailing.Smtp.Password": "Password";
  "DisplayName:Abp.Mailing.Smtp.Domain": "Domain";
  "DisplayName:Abp.Mailing.Smtp.EnableSsl": "Enable SSL";
  "DisplayName:Abp.Mailing.Smtp.UseDefaultCredentials": "Use default credentials";
  "Description:Abp.Mailing.DefaultFromAddress": "The default from address";
  "Description:Abp.Mailing.DefaultFromDisplayName": "The default from display name";
  "Description:Abp.Mailing.Smtp.Host": "The name or IP address of the host used for SMTP transactions.";
  "Description:Abp.Mailing.Smtp.Port": "The port used for SMTP transactions.";
  "Description:Abp.Mailing.Smtp.UserName": "User name associated with the credentials.";
  "Description:Abp.Mailing.Smtp.Password": "The password for the user name associated with the credentials.";
  "Description:Abp.Mailing.Smtp.Domain": "The domain or computer name that verifies the credentials.";
  "Description:Abp.Mailing.Smtp.EnableSsl": "Whether the SmtpClient uses Secure Sockets Layer (SSL) to encrypt the connection.";
  "Description:Abp.Mailing.Smtp.UseDefaultCredentials": "Whether the DefaultCredentials are sent with requests.";
  "TextTemplate:StandardEmailTemplates.Layout": "Default email layout template";
  "TextTemplate:StandardEmailTemplates.Message": "Simple message template for emails";
};
